language: go
go:
  - 1.7.3
  - tip

env:
  global:
    - GITHUB_REPO: missdeer/ddnsclient
    - GIT_NAME: missdeer
    - GIT_EMAIL: missdeer@dfordsoft.com

deploy:
  provider: releases
  api_key:
      secure: Putn2dfCb7wEXFZ5yF/TFo8HHiyIGf7b80C5lJHB4YTKxKBic8xOd3v6IhVfXNZgHSvuA+TVDI9VQJ9eRviJalCVN1qP88oLlrj4/q1WeF9DDUxpTPHV1uP/z6F8s0nmyICRFPs7Gq0fUyfZae+DgF0uaZT+6VxDksjg25eYFFQ=
  file: $GOPATH/bin/ddnsclient
  skip_cleanup: true
  on:
    tags: true
